services:
  apex-backend:
    volumes:
      - .:/app
    environment:
      - BASE_PATH=
      - DEV_MODE=true
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@apex-db:5432/apex_db
      - ALLOW_SQLITE_FALLBACK=false

  apex-frontend:
    volumes:
      # Mount the local frontend folder so HMR works on local file saves
      - ./frontend:/app
      # Do not mount local node_modules over the container's node_modules
      - /app/node_modules
    environment:
      - BASE_PATH=
